export enum UserProperty {
	ID = 'id',
	FIRST_NAME = 'first_name',
	LAST_NAME = 'last_name',
	EMAIL = 'email',
	PASSWORD_HASH = 'password_hash',
	GENDER = 'gender',
	AGE_GROUP_START = 'age_group_start',
	ACTIVITY_TIME_1 = 'activity_time_1',
	ACTIVITY_TIME_2 = 'activity_time_2',
	ACTIVITY_TIME_3 = 'activity_time_3',
	ACTIVITY_TIME_4 = 'activity_time_4',
	CURRENT_STEP = 'current_step',
	CURRENT_DAY = 'current_day',
	CURRENT_ACTIVITY = 'current_activity',
}
